# Generated by Django 3.0.4 on 2020-03-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='couse_code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='couse_name',
            new_name='course_name',
        ),
    ]
