# Generated by Django 3.0.4 on 2020-03-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='prof',
            new_name='course_name',
        ),
    ]
