# Generated by Django 3.0.4 on 2020-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200328_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviewer',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
