# Generated by Django 3.0.4 on 2020-03-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=250)),
                ('prof_department', models.CharField(max_length=500)),
                ('prof_pic', models.CharField(max_length=5000)),
            ],
        ),
    ]
