# Generated by Django 3.0.4 on 2020-03-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='professors',
            name='prof_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.departments'),
        ),
    ]
