# Generated by Django 3.0.4 on 2020-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_auto_20200325_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='review_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professors',
            name='review_sum',
            field=models.IntegerField(default=0),
        ),
    ]
