# Generated by Django 3.0.4 on 2020-03-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_auto_20200325_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='prof_mail',
            field=models.CharField(default='Not available', max_length=100),
        ),
        migrations.AddField(
            model_name='professors',
            name='prof_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professors',
            name='prof_position',
            field=models.CharField(default='Not available', max_length=100),
        ),
        migrations.AddField(
            model_name='professors',
            name='prof_ra',
            field=models.CharField(default='Not available', max_length=1000),
        ),
    ]
