# Generated by Django 3.0.4 on 2020-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_auto_20200325_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='prof_phone',
            field=models.CharField(default='Not available', max_length=50),
        ),
    ]
