# Generated by Django 3.0.4 on 2020-03-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_auto_20200325_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review_det', models.CharField(max_length=500)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.departments')),
            ],
        ),
    ]
