# Generated by Django 3.0.4 on 2020-03-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professors'),
        ),
    ]
