# Generated by Django 3.0.4 on 2020-03-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_auto_20200330_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review_det',
            new_name='comment',
        ),
    ]
