# Generated by Django 3.0.4 on 2020-03-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0011_remove_reviews_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='comment',
            new_name='review_det',
        ),
    ]
