# Generated by Django 3.0.4 on 2020-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0012_auto_20200330_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviewer',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
