# Generated by Django 3.0.4 on 2020-03-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0013_reviews_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review_det',
            new_name='comment',
        ),
    ]
