# Generated by Django 3.0.4 on 2020-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0014_auto_20200330_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
